CREATE TYPE "public"."model_pricing_operation" AS ENUM('chat_input', 'chat_output', 'chat_cached_input', 'embedding', 'rerank');--> statement-breakpoint
CREATE TYPE "public"."model_pricing_unit" AS ENUM('per_million_tokens', 'per_request', 'per_1k_tokens');--> statement-breakpoint
CREATE TABLE "model_pricing" (
	"id" text PRIMARY KEY NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"operation" "model_pricing_operation" NOT NULL,
	"price_micros_per_unit" bigint NOT NULL,
	"unit" "model_pricing_unit" NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"effective_to" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "model_pricing_lookup_idx" ON "model_pricing" USING btree ("provider","model","operation","effective_from");
--> statement-breakpoint
-- Seed model pricing from packages/billing/src/pricing/seed.json (source of truth).
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_gpt4o_mini_in', 'openai', 'gpt-4o-mini', 'chat_input', 150000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_gpt4o_mini_out', 'openai', 'gpt-4o-mini', 'chat_output', 600000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_gpt4o_mini_cached', 'openai', 'gpt-4o-mini', 'chat_cached_input', 75000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_gpt4o_in', 'openai', 'gpt-4o', 'chat_input', 2500000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_gpt4o_out', 'openai', 'gpt-4o', 'chat_output', 10000000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_gpt4o_cached', 'openai', 'gpt-4o', 'chat_cached_input', 1250000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_default_in', 'openai', '*', 'chat_input', 150000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_default_out', 'openai', '*', 'chat_output', 600000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_default_cached', 'openai', '*', 'chat_cached_input', 75000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_embedding_3_small', 'openai', 'text-embedding-3-small', 'embedding', 20000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_embedding_3_large', 'openai', 'text-embedding-3-large', 'embedding', 130000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_embedding_default', 'openai', '*', 'embedding', 20000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_compatible_default_in', 'openai-compatible', '*', 'chat_input', 150000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_compatible_default_out', 'openai-compatible', '*', 'chat_output', 600000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openai_compatible_embedding', 'openai-compatible', '*', 'embedding', 20000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openrouter_default_in', 'openrouter', '*', 'chat_input', 150000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_openrouter_default_out', 'openrouter', '*', 'chat_output', 600000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_groq_default_in', 'groq', '*', 'chat_input', 50000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_groq_default_out', 'groq', '*', 'chat_output', 100000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_anthropic_default_in', 'anthropic', '*', 'chat_input', 3000000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_anthropic_default_out', 'anthropic', '*', 'chat_output', 15000000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_google_default_in', 'google', '*', 'chat_input', 100000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_google_default_out', 'google', '*', 'chat_output', 400000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_azure_default_in', 'azure', '*', 'chat_input', 150000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_azure_default_out', 'azure', '*', 'chat_output', 600000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_azure_embedding', 'azure', '*', 'embedding', 20000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_cohere_rerank', 'cohere', '*', 'rerank', 2000, 'per_request', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_cohere_embedding', 'cohere', '*', 'embedding', 100000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_voyage_embedding', 'voyage', '*', 'embedding', 60000, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_ollama_chat_in', 'ollama', '*', 'chat_input', 0, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "model_pricing" ("id", "provider", "model", "operation", "price_micros_per_unit", "unit", "effective_from", "effective_to") VALUES ('mp_ollama_chat_out', 'ollama', '*', 'chat_output', 0, 'per_million_tokens', '2026-01-01T00:00:00.000Z', NULL) ON CONFLICT ("id") DO NOTHING;
