/**
 * Deterministic e2e seed — writes `.env.e2e` and generates static fixtures.
 *
 *   node scripts/seed-e2e.mjs
 *
 * Creates e2e@chatai.local / E2ePass123! with a ready refund-policy assistant.
 * Fixtures read the env file (they must not parse this script's console output).
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import postgres from "postgres";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env");
const envE2ePath = path.join(root, ".env.e2e");
const publicE2eDir = path.join(root, "apps/web/public/e2e");
const widgetSource = path.join(root, "apps/web/public/widget/chat.js");
const widgetDist = path.join(root, "packages/widget/dist/chat.js");

if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const i = line.indexOf("=");
    const key = line.slice(0, i);
    const value = line.slice(i + 1);
    if (!process.env[key]) process.env[key] = value;
  }
}

const DATABASE_URL = process.env.DATABASE_URL;
const AI_API_KEY = process.env.AI_API_KEY ?? "";
const AI_BASE_URL = (process.env.AI_BASE_URL ?? "https://api.openai.com/v1").replace(/\/$/, "");
const EMBEDDING_MODEL = process.env.EMBEDDING_MODEL ?? "text-embedding-3-small";
const EMBEDDING_DIMENSIONS = Number(process.env.EMBEDDING_DIMENSIONS ?? "1536");

const E2E_EMAIL = process.env.E2E_EMAIL ?? "e2e@chatai.local";
const E2E_PASSWORD = process.env.E2E_PASSWORD ?? "E2ePass123!";
const E2E_ASSISTANT_ID = process.env.E2E_ASSISTANT_ID ?? "asst_e2e_v02";
const E2E_BASE_URL = process.env.E2E_BASE_URL ?? "http://127.0.0.1:3000";
const E2E_NAME = "E2E User";

if (!DATABASE_URL) {
  console.error("DATABASE_URL is required.");
  process.exit(1);
}

if (!AI_API_KEY) {
  console.error("AI_API_KEY is required to embed the e2e knowledge fixture.");
  process.exit(1);
}

const REFUND_POLICY = `# Refund Policy

We offer a **30-day money-back guarantee** on all paid plans.

- Refunds are processed within 5–7 business days to the original payment method.
- Usage beyond fair trial limits may reduce the refund amount.
- Contact support@example.com to start a refund request.
`;

function id(prefix = "") {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-";
  let out = prefix;
  for (let i = 0; i < 21; i++) out += chars[Math.floor(Math.random() * chars.length)];
  return out;
}

async function hashPassword(password) {
  const cryptoUrl = pathToFileURL(
    path.join(root, "apps/web/node_modules/better-auth/dist/crypto/index.mjs"),
  ).href;
  const mod = await import(cryptoUrl);
  return mod.hashPassword(password);
}

async function embedTexts(texts) {
  const response = await fetch(`${AI_BASE_URL}/embeddings`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${AI_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: EMBEDDING_MODEL,
      input: texts,
      dimensions: EMBEDDING_DIMENSIONS,
    }),
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(data?.error?.message ?? `Embedding failed (${response.status})`);
  }
  const sorted = [...(data.data ?? [])].sort((a, b) => a.index - b.index);
  return sorted.map((row) => row.embedding);
}

function writeEnvE2e() {
  const body = [
    `# Generated by scripts/seed-e2e.mjs — do not commit secrets beyond demo credentials.`,
    `E2E_EMAIL=${E2E_EMAIL}`,
    `E2E_PASSWORD=${E2E_PASSWORD}`,
    `E2E_ASSISTANT_ID=${E2E_ASSISTANT_ID}`,
    `E2E_BASE_URL=${E2E_BASE_URL}`,
    "",
  ].join("\n");
  writeFileSync(envE2ePath, body);
}

function readAssistantIdFromEnvFile() {
  const raw = readFileSync(envE2ePath, "utf8");
  for (const line of raw.split("\n")) {
    if (line.startsWith("E2E_ASSISTANT_ID=")) {
      return line.slice("E2E_ASSISTANT_ID=".length).trim();
    }
  }
  throw new Error("E2E_ASSISTANT_ID missing from .env.e2e");
}

function readBaseUrlFromEnvFile() {
  const raw = readFileSync(envE2ePath, "utf8");
  for (const line of raw.split("\n")) {
    if (line.startsWith("E2E_BASE_URL=")) {
      return line.slice("E2E_BASE_URL=".length).trim();
    }
  }
  return "http://127.0.0.1:3000";
}

function resolveWidgetBundle() {
  if (existsSync(widgetSource)) return widgetSource;
  if (existsSync(widgetDist)) return widgetDist;
  throw new Error(
    "Widget bundle missing. Run `pnpm widget:build` (or `pnpm build`) before seeding e2e fixtures.",
  );
}

function generateFixtures() {
  const assistantPublicId = readAssistantIdFromEnvFile();
  const baseUrl = readBaseUrlFromEnvFile().replace(/\/$/, "");
  mkdirSync(publicE2eDir, { recursive: true });

  const hosted = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>ChatAI e2e hosted widget</title>
  </head>
  <body>
    <main><h1>E2E hosted widget</h1></main>
    <script
      src="/widget/chat.js"
      data-assistant-id="${assistantPublicId}"
      async
    ></script>
  </body>
</html>
`;

  const selfHost = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>ChatAI e2e self-hosted widget</title>
  </head>
  <body>
    <main><h1>E2E self-hosted widget</h1></main>
    <script
      src="./chat.js"
      data-assistant-id="${assistantPublicId}"
      data-api-url="${baseUrl}"
      async
    ></script>
  </body>
</html>
`;

  writeFileSync(path.join(publicE2eDir, "hosted.html"), hosted);
  writeFileSync(path.join(publicE2eDir, "self-host.html"), selfHost);
  copyFileSync(resolveWidgetBundle(), path.join(publicE2eDir, "chat.js"));
}

const passwordHash = await hashPassword(E2E_PASSWORD);
const sql = postgres(DATABASE_URL, { max: 1, prepare: false });

let userId;
const existingUser = await sql`select id from "user" where email = ${E2E_EMAIL} limit 1`;
if (existingUser[0]?.id) {
  userId = existingUser[0].id;
  await sql`
    update account
    set password = ${passwordHash}, updated_at = now()
    where user_id = ${userId} and provider_id = 'credential'
  `;
} else {
  userId = id();
  await sql`
    insert into "user" (id, name, email, email_verified)
    values (${userId}, ${E2E_NAME}, ${E2E_EMAIL}, true)
  `;
  await sql`
    insert into account (id, account_id, provider_id, user_id, password)
    values (${id()}, ${userId}, 'credential', ${userId}, ${passwordHash})
  `;
}

const assistantId = E2E_ASSISTANT_ID;
const publicId = E2E_ASSISTANT_ID;

const existingAssistant = await sql`
  select id from assistants where id = ${assistantId} or public_id = ${publicId} limit 1
`;

if (!existingAssistant[0]?.id) {
  await sql`
    insert into assistants (
      id, public_id, user_id, name, welcome_message, instructions, hallucination_mode, settings
    ) values (
      ${assistantId},
      ${publicId},
      ${userId},
      'E2E Support Bot',
      'Hi! How can I help you today?',
      'Answer using the knowledge base. Cite sources with [1] markers. Do not invent policies. When asked about refunds, mention the 30-day money-back guarantee.',
      'balanced',
      '{}'::jsonb
    )
  `;
} else {
  await sql`
    update assistants
    set
      user_id = ${userId},
      name = 'E2E Support Bot',
      public_id = ${publicId},
      instructions = 'Answer using the knowledge base. Cite sources with [1] markers. Do not invent policies. When asked about refunds, mention the 30-day money-back guarantee.',
      updated_at = now()
    where id = ${assistantId}
  `;
}

const documentName = "Refund policy";
let documentId;
const existingDoc = await sql`
  select id from documents where assistant_id = ${assistantId} and name = ${documentName} limit 1
`;

if (existingDoc[0]?.id) {
  documentId = existingDoc[0].id;
  await sql`delete from chunks where document_id = ${documentId}`;
} else {
  documentId = id();
  await sql`
    insert into documents (
      id, assistant_id, type, name, mime_type, status, content, chunk_count
    ) values (
      ${documentId},
      ${assistantId},
      'text',
      ${documentName},
      'text/plain',
      'processing',
      ${REFUND_POLICY},
      0
    )
  `;
}

const [embedding] = await embedTexts([REFUND_POLICY]);
if (!embedding?.length) {
  throw new Error("Embedding API returned an empty vector.");
}
const chunkId = id();
const vectorLiteral = `[${embedding.join(",")}]`;
await sql`
  insert into chunks (id, document_id, assistant_id, content, embedding, metadata)
  values (
    ${chunkId},
    ${documentId},
    ${assistantId},
    ${REFUND_POLICY},
    ${vectorLiteral}::vector,
    ${sql.json({ heading: "Refund Policy" })}
  )
`;

await sql`
  update documents
  set status = 'ready', error = null, chunk_count = 1, content = ${REFUND_POLICY}, updated_at = now()
  where id = ${documentId}
`;

await sql.end();

writeEnvE2e();
generateFixtures();

console.log("[seed-e2e] Wrote .env.e2e and apps/web/public/e2e fixtures.");
console.log(`[seed-e2e] Assistant ${E2E_ASSISTANT_ID} ready for one chat turn.`);
